version: '3'
services:
  parcel-service:
    container_name: parcel-service
    build:
      context: ./parcel-service
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/parcel
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      - EUREKA_DEFAULT_ZONE=http://eureka-service:8761/eureka
    depends_on:
      - db
      - eureka-service
      - gateway-service

  notification-service:
    container_name: notification-service
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/parcel
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      - EUREKA_DEFAULT_ZONE=http://eureka-service:8761/eureka
    depends_on:
      - db
      - eureka-service
      - gateway-service

  db:
    container_name: db
    image: mysql:8
    volumes:
      - ./docker/db:/var/lib/mysql
      - ./docker/initdb:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - '8090:80'
    depends_on:
      - db

  gateway-service:
    container_name: gateway-service
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    ports:
      - '8888:8888'
    environment:
      - EUREKA_DEFAULT_ZONE=http://eureka-service:8761/eureka
    depends_on:
      - eureka-service

  eureka-service:
    container_name: eureka-service
    build:
      context: ./eureka-service
      dockerfile: Dockerfile
    ports:
      - '8761:8761'